import {
  ConsolidationPlan,
  Domain,
  GroupId,
  GroupMap,
  GroupMapEntry,
  GroupState,
  MembershipPlan,
  OrderPlan,
  OrderUnit,
  ProtectedTabMeta,
  ProtectedTabMetaMap,
  RulesByDomain,
  Tab,
  TabId,
  WindowId,
  asDomain,
  asGroupId,
  asTabId,
  asWindowId,
  extractTabIds,
  isDefined,
  isGrouped,
} from "@/types";
// ============================================================================
// CORE LOGIC (Domain Layer)
// ============================================================================

export function isInternalTab(tab: Tab): boolean {
  if (!tab.url) return false;
  const internalProtocols = [
    "chrome:",
    "about:",
    "edge:",
    "brave:",
    "file:",
    "chrome-extension:",
    "moz-extension:",
  ];
  return internalProtocols.some((p) => tab.url!.startsWith(p));
}

export class TabGroupingService {
  normalizeDomain(domain: string): Domain {
    const d = domain.toLowerCase();
    return asDomain(d.startsWith("www.") ? d.slice(4) : d);
  }

  getDomain(url: string | undefined): Domain {
    if (!url) return asDomain("other");
    try {
      if (url.startsWith("file://")) return asDomain("local-file");

      const u = new URL(url);
      if (
        u.protocol === "chrome-extension:" ||
        u.protocol === "moz-extension:"
      ) {
        return asDomain(u.hostname || "extension");
      }

      // Mandate: Use .host instead of .hostname to include significant ports (e.g. localhost:8000)
      return this.normalizeDomain(u.host);
    } catch {
      return asDomain("other");
    }
  }

  getGroupKey(
    domain: Domain,
    url: string | undefined,
    rulesByDomain: RulesByDomain,
  ): { key: string; title: string } {
    const rule = rulesByDomain[domain];
    const base = rule?.groupName || domain;

    if (typeof rule?.splitByPath === "number" && rule.splitByPath >= 1 && url) {
      try {
        const parts = new URL(url).pathname
          .replace(/\/$/, "")
          .replace(/^\//, "")
          .split("/")
          .filter(Boolean);

        if (parts.length >= rule.splitByPath) {
          const segs = parts.slice(0, rule.splitByPath);
          const pathKey = segs.join("/");
          const lastSeg = segs[segs.length - 1];
          return {
            key: `${domain}::${pathKey}`,
            title: `${lastSeg} - ${rule.groupName || domain}`,
          };
        }
      } catch {
        /* fallback */
      }
    }

    return { key: base, title: base };
  }

  /**
   * Heuristic to determine if a group title was likely generated by this extension.
   * This is critical for distinguishing "Managed" (by us) vs "Manual" (by user) groups.
   */
  isInternalTitle(
    title: string,
    domain: Domain,
    url: string | undefined,
    rulesByDomain: RulesByDomain,
  ): boolean {
    if (!title) return false; // Mandate: Unnamed groups are treated as manual/protected

    const t = title.toLowerCase();
    const d = domain.toLowerCase();

    // 1. Early exit: Check for exact domain match or common prefix/suffix variants
    if (t === d || t === `www.${d}`) return true;

    const rule = rulesByDomain[domain];
    const base = (rule?.groupName || domain).toLowerCase();

    // 2. Base name match (case-insensitive)
    if (t === base || t === `www.${base}`) return true;

    // 3. Expected title from current rule match
    const { title: expected } = this.getGroupKey(domain, url, rulesByDomain);
    const e = expected.toLowerCase();
    if (t === e) return true;

    // 4. Collision-resolved variants (e.g. "google.com - Search")
    if (
      t.endsWith(` - ${e}`) ||
      t.endsWith(` - ${d}`) ||
      t.endsWith(` - ${base}`)
    ) {
      return true;
    }

    // 5. Split-path variants (e.g. "github.com/microsoft")
    // Mandate: Only reclaim titles that follow the 'segment - base' or 'segment/base' pattern.
    // We avoid 'base - segment' variants to protect user-named groups.
    if (t.includes(" - ")) {
      if (
        t.endsWith(` - ${d}`) ||
        t.endsWith(` - ${base}`) ||
        t.endsWith(` - www.${d}`) ||
        t.endsWith(` - www.${base}`)
      )
        return true;
    }

    if (t.includes("/")) {
      if (
        t.startsWith(`${d}/`) ||
        t.startsWith(`${base}/`) ||
        t.startsWith(`www.${d}/`) ||
        t.startsWith(`www.${base}/`)
      )
        return true;
    }

    return false;
  }

  private getTabsByGroup(tabs: Tab[]): Map<number, Tab[]> {
    const tabsByGroup = new Map<number, Tab[]>();
    for (const tab of tabs) {
      if (isGrouped(tab)) {
        const gid = tab.groupId!;
        if (!tabsByGroup.has(gid)) tabsByGroup.set(gid, []);
        tabsByGroup.get(gid)!.push(tab);
      }
    }
    return tabsByGroup;
  }

  identifyProtectedTabs(
    tabs: Tab[],
    groupIdToGroup: Map<number, chrome.tabGroups.TabGroup>,
    rulesByDomain: RulesByDomain,
  ): {
    protectedMeta: ProtectedTabMetaMap;
    managedGroupIds: Map<number, string>;
  } {
    const protectedMeta = new Map<TabId, ProtectedTabMeta>();
    const managedGroupIds = new Map<number, string>();
    const tabsByGroup = this.getTabsByGroup(tabs);

    for (const [gid, gTabs] of tabsByGroup.entries()) {
      const g = groupIdToGroup.get(gid);
      if (!g) continue;

      const title = g.title || "";
      // Mandate: A group is "Managed" if it has a title that matches the domain-grouping logic
      // for AT LEAST one of its member tabs. This is a best-effort heuristic to avoid
      // destroying manual user groups while still "reclaiming" extension-owned groups.
      const isManaged = gTabs.some((t) => {
        const domain = this.getDomain(t.url);
        const normalizedDomain = this.normalizeDomain(domain);
        return this.isInternalTitle(
          title,
          normalizedDomain,
          t.url,
          rulesByDomain,
        );
      });

      if (!isManaged) {
        for (const t of gTabs) {
          protectedMeta.set(asTabId(t.id)!, {
            title: title,
            originalGroupId: g.id,
          });
        }
      } else {
        managedGroupIds.set(gid, title);
      }
    }
    return { protectedMeta, managedGroupIds };
  }

  buildGroupMap(
    tabs: Tab[],
    rulesByDomain: RulesByDomain,
    groupIdToGroup?: Map<number, chrome.tabGroups.TabGroup>,
    protectedTabMeta: ProtectedTabMetaMap = new Map(),
  ): GroupMap {
    const map = new Map<string, GroupMapEntry>();
    for (const tab of tabs) {
      const tabId = asTabId(tab.id);
      const domain = this.getDomain(tab.url);

      let isExternal = false;
      let groupKey: string = "";
      let displayName: string = "";
      let groupId: GroupId | null = null;
      let collapsed = false;

      const meta = tabId ? protectedTabMeta.get(tabId) : undefined;
      if (meta) {
        isExternal = true;
        groupKey = `external::${meta.originalGroupId}`;
        displayName = meta.title;
        groupId = asGroupId(meta.originalGroupId);

        const group = groupIdToGroup?.get(meta.originalGroupId);
        if (group) {
          collapsed = group.collapsed;
        }
      } else if (tabId && isGrouped(tab) && groupIdToGroup) {
        const group = groupIdToGroup.get(tab.groupId!);
        const groupTitle = group?.title || "";
        if (this.isInternalTitle(groupTitle, domain, tab.url, rulesByDomain)) {
          const { key, title } = this.getGroupKey(
            domain,
            tab.url,
            rulesByDomain,
          );
          groupKey = `${tab.pinned ? "pinned" : "unpinned"}::${key}`;
          displayName = title;

          // Mandate: Only inherit groupId if the title specifically matches what we expect for this tab
          // This ensures that path-segment intruders are seen as needing to move to their OWN group
          // OR if the current group has NO title, we inherit it to allow for a rename (scavenge).
          if (
            groupTitle === "" ||
            groupTitle.toLowerCase() === title.toLowerCase()
          ) {
            groupId = asGroupId(tab.groupId!);
            collapsed = group?.collapsed || false;
          }
        }
      }

      if (!groupKey) {
        const { key, title } = this.getGroupKey(domain, tab.url, rulesByDomain);
        groupKey = `${tab.pinned ? "pinned" : "unpinned"}::${key}`;
        displayName = title;
      }

      const existing = map.get(groupKey);
      map.set(
        groupKey,
        existing
          ? {
              tabs: [...existing.tabs, tab],
              displayName: existing.displayName, // Stable: keep the first one
              domains: new Set([...existing.domains, domain]),
              isExternal: isExternal || existing.isExternal,
              groupId: groupId || existing.groupId,
              collapsed: collapsed || existing.collapsed,
            }
          : {
              tabs: [tab],
              displayName,
              domains: new Set([domain]),
              isExternal,
              groupId,
              collapsed,
            },
      );
    }
    return map;
  }

  getCleanupTabIds(tabs: Tab[], rulesByDomain: RulesByDomain): Set<TabId> {
    const seen = new Set<string>();
    const toRemove = new Set<TabId>();
    for (const tab of tabs) {
      if (!tab.id || !tab.url) continue;
      const tid = asTabId(tab.id)!;

      // 1. Auto-delete check
      const domain = this.getDomain(tab.url);
      const rule = rulesByDomain[domain];
      if (rule?.autoDelete) {
        toRemove.add(tid);
        continue;
      }

      // 2. Duplicate check
      if (seen.has(tab.url)) {
        toRemove.add(tid);
      } else {
        seen.add(tab.url);
      }
    }
    return toRemove;
  }

  calculateInternalPageMoves(
    tabs: Tab[],
  ): { tabId: TabId; targetIndex: number }[] {
    const moves: { tabId: TabId; targetIndex: number }[] = [];
    const windowMap = new Map<number, Tab[]>();

    for (const tab of tabs) {
      if (tab.windowId === undefined) continue;
      if (!windowMap.has(tab.windowId)) windowMap.set(tab.windowId, []);
      windowMap.get(tab.windowId)!.push(tab);
    }

    for (const wTabs of windowMap.values()) {
      const internalUnpinned = wTabs.filter(
        (t) => isInternalTab(t) && !t.pinned,
      );
      if (internalUnpinned.length === 0) continue;

      // Stable sort by URL
      const sorted = [...internalUnpinned].sort((a, b) =>
        (a.url || "").localeCompare(b.url || ""),
      );

      const pinnedCount = wTabs.filter((t) => t.pinned).length;
      let targetIdx = pinnedCount;

      for (const tab of sorted) {
        if (tab.id && tab.index !== targetIdx) {
          moves.push({ tabId: asTabId(tab.id)!, targetIndex: targetIdx });
        }
        targetIdx++;
      }
    }
    return moves;
  }

  private mapRawStates(
    groupMap: GroupMap,
    tabCache: ReadonlyMap<TabId, Tab>,
  ): GroupState[] {
    const rawStates: GroupState[] = [];
    for (const {
      tabs,
      displayName,
      domains,
      isExternal,
      groupId: entryGroupId,
      collapsed,
    } of groupMap.values()) {
      const valid = extractTabIds(tabs)
        .map((id) => tabCache.get(id))
        .filter(isDefined)
        .filter((t) => {
          if (isExternal) return true;
          return domains.has(this.getDomain(t.url));
        });

      if (valid.length === 0) continue;

      const domainsArray = Array.from(domains);
      const sourceDomain = (domainsArray[0] as string) || "other";
      rawStates.push({
        displayName: isExternal ? displayName : displayName || sourceDomain,
        sourceDomain,
        tabIds: extractTabIds(valid),
        groupId: entryGroupId || null,
        collapsed: collapsed || false,
        needsReposition: false,
        isExternal,
      });
    }
    return rawStates;
  }

  private resolveGroupCollisions(
    rawStates: GroupState[],
    tabCache: ReadonlyMap<TabId, Tab>,
  ): GroupState[] {
    const merged = new Map<string, GroupState>();

    for (const s of rawStates) {
      if (s.isExternal) {
        const key = `external::${s.groupId}::${s.displayName}`;
        merged.set(key, s);
        continue;
      }

      const isPinned = tabCache.get(s.tabIds[0])?.pinned
        ? "pinned"
        : "unpinned";
      const key = `${isPinned}::${s.sourceDomain.toLowerCase()}::${s.displayName.toLowerCase()}`;
      const existing = merged.get(key);
      if (existing) {
        merged.set(key, {
          ...existing,
          tabIds: [...existing.tabIds, ...s.tabIds],
          groupId: existing.groupId || s.groupId,
          collapsed: existing.collapsed || s.collapsed,
        });
      } else {
        merged.set(key, s);
      }
    }
    return Array.from(merged.values());
  }

  buildGroupStates(
    groupMap: GroupMap,
    tabCache: ReadonlyMap<TabId, Tab>,
    groupsByTitle?: Map<string, GroupId>,
    managedGroupIds: Map<number, string> = new Map(),
  ): GroupState[] {
    const rawStates = this.mapRawStates(groupMap, tabCache);
    const initial = this.resolveGroupCollisions(rawStates, tabCache);

    // Mandate: Stable and functional sort for tabs within groups
    const sorted = initial.map((s) => {
      if (s.isExternal) return s;

      const valid = s.tabIds.map((id) => tabCache.get(id)).filter(isDefined);
      valid.sort((a, b) => {
        const urlComp = (a.url || "").localeCompare(b.url || "");
        if (urlComp !== 0) return urlComp;
        return (a.id ?? 0) - (b.id ?? 0); // Stability fallback
      });

      return {
        ...s,
        tabIds: extractTabIds(valid),
      };
    });

    const titleCounts = new Map<string, number>();
    for (const s of sorted)
      titleCounts.set(s.displayName, (titleCounts.get(s.displayName) || 0) + 1);

    const resolved = sorted.map((s) => {
      if (s.isExternal || (titleCounts.get(s.displayName) || 0) <= 1) return s;

      const prefix = s.sourceDomain;
      if (s.displayName.toLowerCase().includes(prefix.toLowerCase())) return s;

      return {
        ...s,
        displayName: `${prefix} - ${s.displayName}`,
      };
    });

    return resolved.map((s) => {
      const validTabs = s.tabIds
        .map((id) => tabCache.get(id))
        .filter(isDefined);

      const existing = validTabs.find((t) => {
        if (!isGrouped(t)) return false;
        const currentTitle = managedGroupIds.get(t.groupId!);
        return currentTitle === s.displayName;
      });

      let groupId =
        s.groupId != null
          ? s.groupId
          : existing?.groupId != null
            ? asGroupId(existing.groupId)
            : (s.displayName && groupsByTitle?.get(s.displayName)) || null;

      // Grouping threshold: 2+ tabs with same group key (domain + path) → group, 1 tab → ungroup.
      if (!s.isExternal && s.tabIds.length < 2) {
        groupId = null;
      }

      // Mandate: Managed pinned tabs are never grouped
      const firstTab = tabCache.get(s.tabIds[0]);
      if (!s.isExternal && firstTab?.pinned) {
        groupId = null;
      }

      return { ...s, groupId };
    });
  }

  private validateGroupState(
    state: GroupState,
    tabCache: ReadonlyMap<TabId, Tab>,
    tabsInGroupCount: Map<number, number>,
    tabsInGroupIdMap: Map<number, Set<TabId>>,
    expectedIndex: number,
    windowId?: WindowId,
  ): boolean {
    const consistent = state.tabIds.every((id, i) => {
      const tab = tabCache.get(id);
      if (!tab) return false;

      const rightWindow = windowId === undefined || tab.windowId === windowId;
      const rightIndex = tab.index === expectedIndex + i;
      const rightGroup =
        state.groupId !== null || state.isExternal || state.tabIds.length >= 2
          ? tab.groupId === state.groupId
          : tab.groupId === -1;
      return rightWindow && rightIndex && rightGroup;
    });
    if (!consistent) return false;

    if (
      state.groupId !== null &&
      (state.isExternal || state.tabIds.length >= 2)
    ) {
      if (
        (tabsInGroupCount.get(state.groupId as number) || 0) !==
        state.tabIds.length
      )
        return false;
      const ids = tabsInGroupIdMap.get(state.groupId as number);
      if (!ids || !state.tabIds.every((id) => ids.has(id))) return false;
    } else if (state.tabIds.length === 1 && !state.isExternal) {
      const tab = tabCache.get(state.tabIds[0]);
      if (tab && isGrouped(tab)) return false;
    }

    return true;
  }

  private getSortingStrategies(tabCache: ReadonlyMap<TabId, Tab>) {
    const sortByUrl = (a: GroupState, b: GroupState) => {
      const nameComp = (a.displayName || "").localeCompare(b.displayName || "");
      if (nameComp !== 0) return nameComp;

      const tA = tabCache.get(a.tabIds[0]);
      const tB = tabCache.get(b.tabIds[0]);
      const urlComp = (tA?.url || "").localeCompare(tB?.url || "");
      if (urlComp !== 0) return urlComp;
      return (tA?.id ?? 0) - (tB?.id ?? 0);
    };

    const sortById = (a: GroupState, b: GroupState) => {
      const nameComp = (a.displayName || "").localeCompare(b.displayName || "");
      if (nameComp !== 0) return nameComp;

      const tA = tabCache.get(a.tabIds[0]);
      const tB = tabCache.get(b.tabIds[0]);
      return (tA?.id ?? 0) - (tB?.id ?? 0);
    };

    return { sortByUrl, sortById };
  }

  // ============================================================================
  // SORTING & REPOSITIONING
  // ============================================================================

  public compareTabOrder(a: Tab, b: Tab): number {
    if (a.pinned !== b.pinned) return a.pinned ? -1 : 1;

    const isInternalA = isInternalTab(a);
    const isInternalB = isInternalTab(b);
    if (isInternalA !== isInternalB) return isInternalA ? -1 : 1;

    // Use groupId as proxy for "is clustered"
    const isGroupedA = (a.groupId ?? -1) !== -1;
    const isGroupedB = (b.groupId ?? -1) !== -1;
    if (isGroupedA !== isGroupedB) return isGroupedA ? -1 : 1;

    const domainA = this.getDomain(a.url);
    const domainB = this.getDomain(b.url);
    if (domainA !== domainB) return domainA.localeCompare(domainB);

    return (a.url || "").localeCompare(b.url || "");
  }

  calculateRepositionNeeds(
    groupStates: GroupState[],
    tabCache: ReadonlyMap<TabId, Tab>,
    windowId?: WindowId,
    managedGroupIds: Map<number, string> = new Map(),
  ): GroupState[] {
    const allTabs = Array.from(tabCache.values());

    // Mandate: Stable and comprehensive sort for all candidate tabs
    allTabs.sort((a, b) => {
      if (a.windowId !== b.windowId)
        return (a.windowId || 0) - (b.windowId || 0);
      return a.index - b.index;
    });

    const managed = new Set(groupStates.flatMap((s) => s.tabIds));
    const ignoredPinned = allTabs.filter(
      (t) => t.pinned && !managed.has(asTabId(t.id)!),
    );

    const { sortByUrl, sortById } = this.getSortingStrategies(tabCache);

    const managedPinned = groupStates
      .filter((s) => tabCache.get(s.tabIds[0])?.pinned)
      .sort((a, b) => {
        const isGroupA = a.isExternal || a.tabIds.length >= 2 ? 1 : 0;
        const isGroupB = b.isExternal || b.tabIds.length >= 2 ? 1 : 0;
        if (isGroupA !== isGroupB) return isGroupA ? -1 : 1;
        if (a.isExternal !== b.isExternal) return a.isExternal ? -1 : 1;
        return sortById(a, b);
      });

    const managedUnpinned = groupStates
      .filter((s) => !tabCache.get(s.tabIds[0])?.pinned)
      .sort((a, b) => {
        const tA = tabCache.get(a.tabIds[0]);
        const tB = tabCache.get(b.tabIds[0]);
        const isInternalA = tA ? isInternalTab(tA) : false;
        const isInternalB = tB ? isInternalTab(tB) : false;

        // Mandate: Internal Pages -> Clustered Groups -> Title/URL
        if (isInternalA !== isInternalB) return isInternalA ? -1 : 1;

        const isGroupA = a.isExternal || a.tabIds.length >= 2 ? 1 : 0;
        const isGroupB = b.isExternal || b.tabIds.length >= 2 ? 1 : 0;
        if (isGroupA !== isGroupB) return isGroupB - isGroupA;

        return sortByUrl(a, b);
      });

    const tabsInGroupCount = new Map<number, number>();
    const tabsInGroupIdMap = new Map<number, Set<TabId>>();

    const tabsByGroup = this.getTabsByGroup(allTabs);
    for (const [gid, tabs] of tabsByGroup.entries()) {
      tabsInGroupCount.set(gid, tabs.length);
      tabsInGroupIdMap.set(gid, new Set(tabs.map((t) => asTabId(t.id)!)));
    }

    const results: GroupState[] = [];
    let idx = ignoredPinned.length;

    const processStates = (states: GroupState[]) => {
      for (const s of states) {
        const needsReposition = !this.validateGroupState(
          s,
          tabCache,
          tabsInGroupCount,
          tabsInGroupIdMap,
          idx,
          windowId,
        );
        const currentTitle =
          s.groupId !== null ? managedGroupIds.get(s.groupId as number) : null;
        const needsTitleUpdate =
          s.groupId !== null &&
          currentTitle !== null &&
          currentTitle !== s.displayName;

        results.push({
          ...s,
          needsReposition,
          needsTitleUpdate,
          targetIndex: idx,
        });
        idx += s.tabIds.length;
      }
    };

    processStates(managedPinned);
    processStates(managedUnpinned);

    return results;
  }

  buildMembershipPlan(
    groupStates: GroupState[],
    tabCache: ReadonlyMap<TabId, Tab>,
    managedGroupIds: Map<number, string>,
    windowId: WindowId,
  ): MembershipPlan {
    const toUngroup: TabId[] = [];
    const toGroup: MembershipPlan["toGroup"] = [];

    // Track which tabs belong to which group in the intended state
    const groupToExpectedTabs = new Map<number, Set<TabId>>();
    for (const s of groupStates) {
      if (s.groupId !== null) {
        if (!groupToExpectedTabs.has(s.groupId))
          groupToExpectedTabs.set(s.groupId, new Set());
        for (const id of s.tabIds) groupToExpectedTabs.get(s.groupId)!.add(id);
      }
    }

    // 1. Identify tabs that need to be UNGROUPED
    // A tab needs ungrouping if it's currently in a managed group but doesn't belong there in the plan
    for (const tab of tabCache.values()) {
      if (tab.windowId !== windowId) continue;
      const tid = asTabId(tab.id);
      const gid = tab.groupId;

      if (tid && gid !== -1 && isDefined(gid)) {
        if (managedGroupIds.has(gid)) {
          const expected = groupToExpectedTabs.get(gid);
          if (!expected || !expected.has(tid)) {
            toUngroup.push(tid);
          }
        }
      }
    }

    // 2. Identify groups that need to be (RE)CREATED or TITLED
    // Any group in the plan with 2+ tabs (or external) needs a toGroup entry
    for (const s of groupStates) {
      if (s.isExternal || s.tabIds.length >= 2) {
        toGroup.push({
          tabIds: [...s.tabIds],
          groupId: s.groupId,
          title: s.displayName,
          collapsed: s.collapsed,
        });
      }
    }

    return { toUngroup, toGroup, targetWindowId: windowId };
  }

  buildOrderPlan(desired: OrderUnit[], liveUnits: OrderUnit[]): OrderPlan {
    const liveKeys = liveUnits.map((u) => this.unitKey(u));
    const desiredKeys = desired.map((u) => this.unitKey(u));

    // Map each desired key to its current index in live state
    const liveIndexMap = new Map<string, number>();
    liveKeys.forEach((key, idx) => liveIndexMap.set(key, idx));

    // Filter desired units to those that exist in the live snapshot for THIS window
    // AND are at their correct absolute target position.
    // If a unit is interleaved with unmanaged tabs, its targetIndex won't match its current index.
    const indices: number[] = [];
    const candidatesForLIS: number[] = []; // Indices in 'desired' list

    desired.forEach((unit, dIdx) => {
      const key = this.unitKey(unit);
      const lIdx = liveIndexMap.get(key);
      if (lIdx !== undefined) {
        const liveUnit = liveUnits[lIdx];
        // Mandate: A unit is only a candidate for staying (LIS) if its
        // current absolute position matches its target absolute position.
        // This ensures unmanaged tabs are displaced correctly to the end.
        if (liveUnit.targetIndex === unit.targetIndex) {
          indices.push(lIdx);
          candidatesForLIS.push(dIdx);
        }
      }
    });

    // LIS algorithm to find the largest subset of units already in order
    const lisSubsequenceIndices = this.calculateLIS(indices);
    const inOrderKeys = new Set(
      lisSubsequenceIndices.map((i) => desiredKeys[candidatesForLIS[i]]),
    );

    const toMove = desired.filter((u) => !inOrderKeys.has(this.unitKey(u)));

    return {
      desired,
      toMove,
    };
  }

  mapToOrderUnits(states: GroupState[]): OrderUnit[] {
    const units: OrderUnit[] = [];
    for (const s of states) {
      const isActuallyGrouped =
        (s.isExternal || s.tabIds.length >= 2) && s.groupId !== null;

      if (isActuallyGrouped) {
        units.push({
          kind: "group",
          groupId: s.groupId as GroupId,
          tabIds: [...s.tabIds],
          targetIndex: s.targetIndex ?? 0,
        });
      } else {
        // Treat as individual tabs
        s.tabIds.forEach((tid, i) => {
          units.push({
            kind: "solo",
            tabId: tid,
            targetIndex: (s.targetIndex ?? 0) + i,
          });
        });
      }
    }
    return units;
  }

  getLiveUnits(tabs: Tab[]): OrderUnit[] {
    const live: OrderUnit[] = [];
    const seenGroups = new Set<number>();

    for (const t of tabs) {
      if (isGrouped(t)) {
        if (!seenGroups.has(t.groupId)) {
          seenGroups.add(t.groupId);
          const gTabs = tabs.filter((gt) => gt.groupId === t.groupId);
          live.push({
            kind: "group",
            groupId: asGroupId(t.groupId),
            tabIds: extractTabIds(gTabs),
            targetIndex: t.index,
          });
        }
      } else {
        live.push({
          kind: "solo",
          tabId: asTabId(t.id)!,
          targetIndex: t.index,
        });
      }
    }
    return live;
  }

  private unitKey(u: OrderUnit): string {
    return u.kind === "group" ? `g:${u.groupId}` : `t:${u.tabId}`;
  }

  // ============================================================================
  // PERFORMANCE UTILITIES (Hashing)
  // ============================================================================

  /**
   * High-performance 32-bit FNV-1a hash implementation.
   * Optimized for zero-allocation state fingerprinting.
   */
  hashState(
    tabs: Tab[],
    groupIdToGroup: Map<number, chrome.tabGroups.TabGroup>,
  ): string {
    let h = 2166136261 >>> 0; // FNV offset basis

    const update = (val: number) => {
      h ^= val >>> 0;
      h = Math.imul(h, 16777619);
    };

    const updateString = (str: string) => {
      for (let i = 0; i < str.length; i++) {
        update(str.charCodeAt(i));
      }
    };

    // 1. Stable Tab Hashing
    const sortedTabs = [...tabs].sort((a, b) => (a.id ?? 0) - (b.id ?? 0));
    for (const t of sortedTabs) {
      update(t.id ?? 0);
      update(t.groupId ?? -1);
      update(t.index);
      update(t.windowId ?? 0);
      update(t.pinned ? 1 : 0);
      updateString(t.url || "");
    }

    // 2. Stable Group Hashing
    const sortedGroups = Array.from(groupIdToGroup.values()).sort(
      (a, b) => a.id - b.id,
    );
    for (const g of sortedGroups) {
      update(g.id);
      update(g.collapsed ? 1 : 0);
      updateString(g.title || "");
    }

    return (h >>> 0).toString(16);
  }

  private calculateLIS(arr: number[]): number[] {
    if (arr.length === 0) return [];

    const tails: number[] = [];
    const tailsIndices: number[] = [];
    const prev = new Array(arr.length).fill(-1);

    for (let i = 0; i < arr.length; i++) {
      const x = arr[i];
      let low = 0,
        high = tails.length;
      while (low < high) {
        const mid = (low + high) >>> 1;
        if (tails[mid] < x) low = mid + 1;
        else high = mid;
      }

      if (low < tails.length) {
        tails[low] = x;
        tailsIndices[low] = i;
      } else {
        tails.push(x);
        tailsIndices.push(i);
      }
      prev[i] = low > 0 ? tailsIndices[low - 1] : -1;
    }

    // Backtrack to get the indices of the LIS
    const res: number[] = [];
    let curr = tailsIndices[tailsIndices.length - 1];
    while (curr !== -1) {
      res.push(curr);
      curr = prev[curr];
    }
    return res.reverse();
  }
}

// ============================================================================
// WINDOW MANAGEMENT (Domain Layer)
// ============================================================================

export class WindowManagementService {
  groupByWindow(tabs: Tab[]): Map<WindowId, Tab[]> {
    const map = new Map<WindowId, Tab[]>();
    for (const tab of tabs) {
      if (!tab.windowId) continue;
      const wid = asWindowId(tab.windowId);
      if (!map.has(wid)) map.set(wid, []);
      map.get(wid)!.push(tab);
    }
    return map;
  }

  createConsolidationPlan(
    tabs: Tab[],
    numWindowsToKeep: number,
    service: TabGroupingService,
    protectedTabMeta: ProtectedTabMetaMap,
    managedGroupIds: Map<number, string>,
    targetWindowId: WindowId,
  ): ConsolidationPlan | null {
    const windowGroups = this.groupByWindow(tabs);

    // Mandate: targetWindowId (usually active) is ALWAYS the primary retained window.
    const targetTabs = windowGroups.get(targetWindowId) || [];
    const retained = new Map<WindowId, Tab[]>([[targetWindowId, targetTabs]]);

    // If we can keep more than 1 window, pick the largest remaining ones.
    const others = Array.from(windowGroups.entries())
      .filter(([wid]) => wid !== targetWindowId)
      .sort((a, b) => b[1].length - a[1].length);

    for (let i = 0; i < numWindowsToKeep - 1 && i < others.length; i++) {
      retained.set(others[i][0], others[i][1]);
    }

    const retainedIds = new Set(retained.keys());
    const excess = tabs.filter(
      (t) =>
        t.windowId !== undefined && !retainedIds.has(asWindowId(t.windowId)),
    );

    if (excess.length === 0) return null;

    const mergePlan = this.calculateMergePlan(
      retained,
      excess,
      service,
      protectedTabMeta,
      managedGroupIds,
    );

    const groupMoves: { groupId: number; windowId: WindowId }[] = [];
    const tabMoves: { tabIds: number[]; windowId: WindowId }[] = [];

    // Group the moving tabs by their CURRENT group to identify block moves
    for (const [wid, tabIds] of mergePlan) {
      const targetWinId = asWindowId(wid as number);
      const movingTabs = tabs.filter(
        (t) => t.id && tabIds.includes(asTabId(t.id)!),
      );

      const groupToMovingTabs = new Map<number, number[]>();
      const ungroupedMovingTabs: number[] = [];

      for (const t of movingTabs) {
        if (isGrouped(t)) {
          if (!groupToMovingTabs.has(t.groupId!))
            groupToMovingTabs.set(t.groupId!, []);
          groupToMovingTabs.get(t.groupId!)!.push(t.id!);
        } else {
          ungroupedMovingTabs.push(t.id!);
        }
      }

      for (const [gid, tIds] of groupToMovingTabs.entries()) {
        const allInGroup = tabs.filter((t) => t.groupId === gid);
        if (allInGroup.length === tIds.length) {
          groupMoves.push({ groupId: gid, windowId: targetWinId });
        } else {
          tabMoves.push({ tabIds: tIds, windowId: targetWinId });
        }
      }

      if (ungroupedMovingTabs.length > 0) {
        tabMoves.push({
          tabIds: ungroupedMovingTabs,
          windowId: targetWinId,
        });
      }
    }

    return { groupMoves, tabMoves };
  }

  calculateMergePlan(
    retainedWindows: Map<WindowId, Tab[]>,
    excessTabs: Tab[],
    service: TabGroupingService,
    protectedTabMeta: ProtectedTabMetaMap = new Map(),
    managedGroupIds: Map<number, string> = new Map(),
  ): Map<WindowId, TabId[]> {
    const plan = new Map<WindowId, TabId[]>();
    const domainCounts = new Map<WindowId, Map<Domain, number>>();

    for (const [wid, tabs] of retainedWindows) {
      const counts = new Map<Domain, number>();
      for (const t of tabs) {
        const d = service.getDomain(t.url);
        counts.set(d, (counts.get(d) || 0) + 1);
      }
      domainCounts.set(wid, counts);
    }

    let defaultWid: WindowId | undefined;
    let maxTabs = -1;
    for (const [wid, tabs] of retainedWindows) {
      if (tabs.length > maxTabs) {
        maxTabs = tabs.length;
        defaultWid = wid;
      }
    }

    const groupToTabs = new Map<number, Tab[]>();
    const individualTabs: Tab[] = [];

    // Group all tabs from excess windows by their current grouping status
    for (const tab of excessTabs) {
      if (isGrouped(tab)) {
        const gid = tab.groupId!;
        if (!groupToTabs.has(gid)) groupToTabs.set(gid, []);
        groupToTabs.get(gid)!.push(tab);
      } else {
        individualTabs.push(tab);
      }
    }

    // Assign blocks (current groups) to retained windows based on domain affinity
    for (const gTabs of groupToTabs.values()) {
      const groupDomains = new Map<Domain, number>();
      for (const t of gTabs) {
        const d = service.getDomain(t.url);
        groupDomains.set(d, (groupDomains.get(d) || 0) + 1);
      }

      let bestWid = defaultWid;
      let maxScore = -1;
      for (const [wid, counts] of domainCounts) {
        let score = 0;
        for (const [d, count] of groupDomains) {
          score += (counts.get(d) || 0) * count;
        }
        if (score > maxScore) {
          maxScore = score;
          bestWid = wid;
        }
      }

      if (bestWid) {
        if (!plan.has(bestWid)) plan.set(bestWid, []);
        for (const t of gTabs)
          if (t.id) plan.get(bestWid)!.push(asTabId(t.id)!);
      }
    }

    // Assign solo tabs to retained windows based on domain affinity
    for (const tab of individualTabs) {
      const domain = service.getDomain(tab.url);
      let bestWid = defaultWid;
      let bestCount = 0;
      for (const [wid, counts] of domainCounts) {
        const c = counts.get(domain) || 0;
        if (c > bestCount) {
          bestCount = c;
          bestWid = wid;
        }
      }
      if (bestWid && tab.id) {
        if (!plan.has(bestWid)) plan.set(bestWid, []);
        plan.get(bestWid)!.push(asTabId(tab.id)!);
      }
    }

    return plan;
  }
}
